# Exported from Render on 2025-04-20T04:49:17Z
services:
- type: web
  name: benerp
  runtime: python
  repo: https://github.com/benam40/benerp
  plan: free
  region: frankfurt
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app
version: "1"
